// Emoji categories with icons and emojis
export interface Emoji {
    emoji: string;
    name: string;
    keywords: string[];
}

export interface EmojiCategory {
    id: string;
    name: string;
    icon: string;
    emojis: Emoji[];
}

const RECENT_EMOJIS_KEY = 'recent-emojis';
const MAX_RECENT_EMOJIS = 16;

// Complete emoji catalog organized by categories
export const emojiCategories: EmojiCategory[] = [
    {
        id: 'recent',
        name: 'Recientes',
        icon: '⏱️',
        emojis: [], // This will be populated dynamically
    },
    {
        id: 'smileys',
        name: 'Emociones',
        icon: '😀',
        emojis: [
            { emoji: '😀', name: 'cara sonriente', keywords: ['feliz', 'alegre', 'sonrisa'] },
            { emoji: '😃', name: 'cara sonriente con ojos grandes', keywords: ['feliz', 'alegre'] },
            { emoji: '😄', name: 'cara sonriente con ojos sonrientes', keywords: ['feliz', 'contento'] },
            { emoji: '😁', name: 'cara radiante con ojos sonrientes', keywords: ['feliz', 'radiante'] },
            { emoji: '😆', name: 'cara sonriente con ojos cerrados', keywords: ['risa', 'jaja'] },
            { emoji: '😅', name: 'cara sonriente con sudor', keywords: ['nervioso', 'alivio'] },
            { emoji: '🤣', name: 'rodando de risa', keywords: ['lol', 'carcajada'] },
            { emoji: '😂', name: 'cara llorando de risa', keywords: ['risa', 'llorar'] },
            { emoji: '🙂', name: 'cara ligeramente sonriente', keywords: ['sonrisa', 'leve'] },
            { emoji: '🙃', name: 'cara al revés', keywords: ['sarcasmo', 'tonto'] },
            { emoji: '😉', name: 'cara guiñando', keywords: ['guiño', 'coqueto'] },
            { emoji: '😊', name: 'cara sonriente con ojos sonrientes', keywords: ['tímido', 'sonrojo'] },
            { emoji: '😇', name: 'cara sonriente con aureola', keywords: ['ángel', 'inocente'] },
            { emoji: '🥰', name: 'cara sonriente con corazones', keywords: ['amor', 'enamorado'] },
            { emoji: '😍', name: 'cara con ojos de corazón', keywords: ['amor', 'enamorado'] },
            { emoji: '🤩', name: 'cara con estrellas', keywords: ['wow', 'asombro'] },
            { emoji: '😘', name: 'cara mandando un beso', keywords: ['beso', 'amor'] },
            { emoji: '😗', name: 'cara besando', keywords: ['beso', 'silbando'] },
            { emoji: '☺️', name: 'cara sonriente', keywords: ['feliz', 'contento'] },
            { emoji: '😚', name: 'cara besando con ojos cerrados', keywords: ['beso', 'amor'] },
            { emoji: '😙', name: 'cara besando con ojos sonrientes', keywords: ['beso', 'amor'] },
            { emoji: '🥲', name: 'cara sonriente con lágrima', keywords: ['feliz', 'triste'] },
            { emoji: '😋', name: 'cara saboreando', keywords: ['delicioso', 'yum'] },
            { emoji: '😛', name: 'cara sacando la lengua', keywords: ['lengua', 'juguetón'] },
            { emoji: '😜', name: 'cara sacando la lengua y guiñando', keywords: ['loco', 'juguetón'] },
            { emoji: '🤪', name: 'cara loca', keywords: ['loco', 'tonto'] },
            { emoji: '😝', name: 'cara sacando la lengua con ojos cerrados', keywords: ['lengua', 'juguetón'] },
            { emoji: '🤑', name: 'cara con dinero', keywords: ['dinero', 'rico'] },
            { emoji: '🤗', name: 'cara abrazando', keywords: ['abrazo', 'cariño'] },
            { emoji: '🤭', name: 'cara con mano tapando la boca', keywords: ['ups', 'secreto'] },
            { emoji: '🤫', name: 'cara pidiendo silencio', keywords: ['silencio', 'shh'] },
            { emoji: '🤔', name: 'cara pensando', keywords: ['pensar', 'hmm'] },
            { emoji: '🤐', name: 'cara con la boca cerrada', keywords: ['silencio', 'zipper'] },
            { emoji: '🤨', name: 'cara con ceja levantada', keywords: ['duda', 'escéptico'] },
            { emoji: '😐', name: 'cara neutral', keywords: ['neutral', 'indiferente'] },
            { emoji: '😑', name: 'cara sin expresión', keywords: ['aburrido', 'serio'] },
            { emoji: '😶', name: 'cara sin boca', keywords: ['silencio', 'mudo'] },
            { emoji: '😏', name: 'cara con sonrisa de lado', keywords: ['presumido', 'astuto'] },
            { emoji: '😒', name: 'cara de desaprobación', keywords: ['descontento', 'molesto'] },
            { emoji: '🙄', name: 'cara con ojos en blanco', keywords: ['fastidio', 'aburrido'] },
            { emoji: '😬', name: 'cara con mueca', keywords: ['nervioso', 'incómodo'] },
            { emoji: '🤥', name: 'cara mentirosa', keywords: ['mentira', 'pinocho'] },
            { emoji: '😌', name: 'cara aliviada', keywords: ['paz', 'relajado'] },
            { emoji: '😔', name: 'cara pensativa', keywords: ['triste', 'pensativo'] },
            { emoji: '😪', name: 'cara somnolienta', keywords: ['sueño', 'cansado'] },
            { emoji: '🤤', name: 'cara babeando', keywords: ['hambre', 'delicioso'] },
            { emoji: '😴', name: 'cara durmiendo', keywords: ['dormir', 'zzz'] },
            { emoji: '😷', name: 'cara con mascarilla', keywords: ['enfermo', 'virus'] },
            { emoji: '🤒', name: 'cara con termómetro', keywords: ['fiebre', 'enfermo'] },
            { emoji: '🤕', name: 'cara con vendaje', keywords: ['herido', 'dolor'] },
            { emoji: '🤢', name: 'cara de náusea', keywords: ['asco', 'vómito'] },
            { emoji: '🤮', name: 'cara vomitando', keywords: ['vómito', 'asco'] },
            { emoji: '🤧', name: 'cara estornudando', keywords: ['estornudo', 'gripe'] },
            { emoji: '🥵', name: 'cara acalorada', keywords: ['calor', 'sudor'] },
            { emoji: '🥶', name: 'cara congelada', keywords: ['frío', 'helado'] },
            { emoji: '🥴', name: 'cara mareada', keywords: ['borracho', 'confundido'] },
            { emoji: '😵', name: 'cara con ojos de espiral', keywords: ['mareado', 'aturdido'] },
            { emoji: '🤯', name: 'cabeza explotando', keywords: ['wow', 'mente volada'] },
            { emoji: '🤠', name: 'cara de vaquero', keywords: ['cowboy', 'yeehaw'] },
            { emoji: '🥳', name: 'cara de fiesta', keywords: ['celebrar', 'cumpleaños'] },
            { emoji: '🥸', name: 'cara disfrazada', keywords: ['disfraz', 'incógnito'] },
            { emoji: '😎', name: 'cara con gafas de sol', keywords: ['cool', 'genial'] },
            { emoji: '🤓', name: 'cara de nerd', keywords: ['nerd', 'estudioso'] },
            { emoji: '🧐', name: 'cara con monóculo', keywords: ['investigar', 'hmm'] },
            { emoji: '😕', name: 'cara confundida', keywords: ['confundido', 'triste'] },
            { emoji: '😟', name: 'cara preocupada', keywords: ['preocupado', 'ansioso'] },
            { emoji: '🙁', name: 'cara triste', keywords: ['triste', 'decepcionado'] },
            { emoji: '☹️', name: 'cara con el ceño fruncido', keywords: ['triste', 'enojado'] },
            { emoji: '😮', name: 'cara con la boca abierta', keywords: ['sorprendido', 'wow'] },
            { emoji: '😯', name: 'cara con la boca abierta en silencio', keywords: ['sorprendido', 'asombro'] },
            { emoji: '😲', name: 'cara asombrada', keywords: ['asombrado', 'sorpresa'] },
            { emoji: '😳', name: 'cara sonrojada', keywords: ['sonrojo', 'avergonzado'] },
            { emoji: '🥺', name: 'cara suplicante', keywords: ['por favor', 'triste'] },
            { emoji: '😦', name: 'cara con el ceño fruncido y la boca abierta', keywords: ['preocupado', 'triste'] },
            { emoji: '😧', name: 'cara angustiada', keywords: ['angustia', 'triste'] },
            { emoji: '😨', name: 'cara asustada', keywords: ['miedo', 'susto'] },
            { emoji: '😰', name: 'cara ansiosa con sudor', keywords: ['ansioso', 'nervioso'] },
            { emoji: '😥', name: 'cara triste pero aliviada', keywords: ['triste', 'alivio'] },
            { emoji: '😢', name: 'cara llorando', keywords: ['llorar', 'triste'] },
            { emoji: '😭', name: 'cara llorando a mares', keywords: ['llorar', 'muy triste'] },
            { emoji: '😱', name: 'cara gritando de miedo', keywords: ['miedo', 'terror'] },
            { emoji: '😖', name: 'cara confundida', keywords: ['frustrado', 'confundido'] },
            { emoji: '😣', name: 'cara perseverante', keywords: ['frustrado', 'esfuerzo'] },
            { emoji: '😞', name: 'cara decepcionada', keywords: ['decepcionado', 'triste'] },
            { emoji: '😓', name: 'cara con sudor frío', keywords: ['ansioso', 'preocupado'] },
            { emoji: '😩', name: 'cara agotada', keywords: ['cansado', 'agotado'] },
            { emoji: '😫', name: 'cara cansada', keywords: ['exhausto', 'cansado'] },
            { emoji: '🥱', name: 'cara bostezando', keywords: ['aburrido', 'sueño'] },
            { emoji: '😤', name: 'cara con humo en la nariz', keywords: ['enojado', 'frustrado'] },
            { emoji: '😡', name: 'cara enfurecida', keywords: ['enojado', 'furioso'] },
            { emoji: '😠', name: 'cara enojada', keywords: ['enojado', 'molesto'] },
            { emoji: '🤬', name: 'cara con símbolos en la boca', keywords: ['maldición', 'enojado'] },
            { emoji: '😈', name: 'cara sonriente con cuernos', keywords: ['diablo', 'travieso'] },
            { emoji: '👿', name: 'cara enojada con cuernos', keywords: ['diablo', 'malo'] },
            { emoji: '💀', name: 'calavera', keywords: ['muerte', 'peligro'] },
            { emoji: '☠️', name: 'calavera con huesos', keywords: ['muerte', 'veneno'] },
            { emoji: '💩', name: 'caca', keywords: ['popo', 'mierda'] },
            { emoji: '🤡', name: 'cara de payaso', keywords: ['payaso', 'circo'] },
            { emoji: '👹', name: 'ogro', keywords: ['monstruo', 'demonio'] },
            { emoji: '👺', name: 'duende', keywords: ['monstruo', 'japonés'] },
            { emoji: '👻', name: 'fantasma', keywords: ['halloween', 'boo'] },
            { emoji: '👽', name: 'alienígena', keywords: ['extraterrestre', 'ovni'] },
            { emoji: '👾', name: 'monstruo alienígena', keywords: ['videojuego', 'alien'] },
            { emoji: '🤖', name: 'robot', keywords: ['robot', 'máquina'] },
            { emoji: '😺', name: 'cara de gato sonriente', keywords: ['gato', 'feliz'] },
            { emoji: '😸', name: 'cara de gato sonriente con ojos sonrientes', keywords: ['gato', 'feliz'] },
            { emoji: '😹', name: 'cara de gato llorando de risa', keywords: ['gato', 'risa'] },
            { emoji: '😻', name: 'cara de gato con ojos de corazón', keywords: ['gato', 'amor'] },
            { emoji: '😼', name: 'cara de gato con sonrisa de lado', keywords: ['gato', 'presumido'] },
            { emoji: '😽', name: 'cara de gato besando', keywords: ['gato', 'beso'] },
            { emoji: '🙀', name: 'cara de gato asustado', keywords: ['gato', 'susto'] },
            { emoji: '😿', name: 'cara de gato llorando', keywords: ['gato', 'triste'] },
            { emoji: '😾', name: 'cara de gato enfadado', keywords: ['gato', 'enojado'] },
        ],
    },
    {
        id: 'gestures',
        name: 'Gestos',
        icon: '👋',
        emojis: [
            { emoji: '👋', name: 'mano saludando', keywords: ['hola', 'adios', 'saludo'] },
            { emoji: '🤚', name: 'dorso de la mano', keywords: ['mano', 'stop'] },
            { emoji: '🖐️', name: 'mano con los dedos separados', keywords: ['cinco', 'mano'] },
            { emoji: '✋', name: 'mano levantada', keywords: ['stop', 'alto'] },
            { emoji: '🖖', name: 'saludo vulcano', keywords: ['spock', 'star trek'] },
            { emoji: '👌', name: 'gesto de ok', keywords: ['perfecto', 'bien'] },
            { emoji: '🤌', name: 'dedos juntos', keywords: ['italiano', 'qué'] },
            { emoji: '🤏', name: 'pellizco', keywords: ['pequeño', 'poco'] },
            { emoji: '✌️', name: 'señal de victoria', keywords: ['paz', 'victoria'] },
            { emoji: '🤞', name: 'dedos cruzados', keywords: ['suerte', 'esperanza'] },
            { emoji: '🤟', name: 'te quiero en lenguaje de señas', keywords: ['amor', 'rock'] },
            { emoji: '🤘', name: 'cuernos', keywords: ['rock', 'metal'] },
            { emoji: '🤙', name: 'llámame', keywords: ['teléfono', 'llamar'] },
            { emoji: '👈', name: 'dedo índice apuntando a la izquierda', keywords: ['izquierda', 'señalar'] },
            { emoji: '👉', name: 'dedo índice apuntando a la derecha', keywords: ['derecha', 'señalar'] },
            { emoji: '👆', name: 'dedo índice apuntando hacia arriba', keywords: ['arriba', 'señalar'] },
            { emoji: '🖕', name: 'dedo medio', keywords: ['grosero', 'ofensivo'] },
            { emoji: '👇', name: 'dedo índice apuntando hacia abajo', keywords: ['abajo', 'señalar'] },
            { emoji: '☝️', name: 'dedo índice hacia arriba', keywords: ['uno', 'atención'] },
            { emoji: '👍', name: 'pulgar arriba', keywords: ['bien', 'ok', 'like'] },
            { emoji: '👎', name: 'pulgar abajo', keywords: ['mal', 'no', 'dislike'] },
            { emoji: '✊', name: 'puño levantado', keywords: ['fuerza', 'poder'] },
            { emoji: '👊', name: 'puño acercándose', keywords: ['golpe', 'choque'] },
            { emoji: '🤛', name: 'puño hacia la izquierda', keywords: ['puño', 'choque'] },
            { emoji: '🤜', name: 'puño hacia la derecha', keywords: ['puño', 'choque'] },
            { emoji: '👏', name: 'manos aplaudiendo', keywords: ['aplauso', 'bravo'] },
            { emoji: '🙌', name: 'manos levantadas', keywords: ['celebrar', 'yay'] },
            { emoji: '👐', name: 'manos abiertas', keywords: ['abrazo', 'jazz'] },
            { emoji: '🤲', name: 'palmas juntas hacia arriba', keywords: ['ofrecer', 'pedir'] },
            { emoji: '🤝', name: 'apretón de manos', keywords: ['acuerdo', 'trato'] },
            { emoji: '🙏', name: 'manos juntas', keywords: ['gracias', 'orar', 'namaste'] },
            { emoji: '✍️', name: 'mano escribiendo', keywords: ['escribir', 'firma'] },
            { emoji: '💅', name: 'esmalte de uñas', keywords: ['uñas', 'manicura'] },
            { emoji: '🤳', name: 'selfie', keywords: ['foto', 'móvil'] },
            { emoji: '💪', name: 'bíceps', keywords: ['fuerte', 'músculo'] },
            { emoji: '🦾', name: 'brazo mecánico', keywords: ['robot', 'prótesis'] },
            { emoji: '🦿', name: 'pierna mecánica', keywords: ['robot', 'prótesis'] },
            { emoji: '🦵', name: 'pierna', keywords: ['patear', 'pierna'] },
            { emoji: '🦶', name: 'pie', keywords: ['caminar', 'pie'] },
            { emoji: '👂', name: 'oreja', keywords: ['escuchar', 'oír'] },
            { emoji: '🦻', name: 'oreja con audífono', keywords: ['sordo', 'audífono'] },
            { emoji: '👃', name: 'nariz', keywords: ['oler', 'nariz'] },
            { emoji: '🧠', name: 'cerebro', keywords: ['pensar', 'inteligente'] },
            { emoji: '🫀', name: 'corazón anatómico', keywords: ['corazón', 'órgano'] },
            { emoji: '🫁', name: 'pulmones', keywords: ['respirar', 'órgano'] },
            { emoji: '🦷', name: 'diente', keywords: ['dentista', 'muela'] },
            { emoji: '🦴', name: 'hueso', keywords: ['esqueleto', 'perro'] },
            { emoji: '👀', name: 'ojos', keywords: ['mirar', 'ver'] },
            { emoji: '👁️', name: 'ojo', keywords: ['ver', 'mirar'] },
            { emoji: '👅', name: 'lengua', keywords: ['saborear', 'lengua'] },
            { emoji: '👄', name: 'boca', keywords: ['labios', 'besar'] },
        ],
    },
    {
        id: 'hearts',
        name: 'Amor',
        icon: '❤️',
        emojis: [
            { emoji: '❤️', name: 'corazón rojo', keywords: ['amor', 'corazón'] },
            { emoji: '🧡', name: 'corazón naranja', keywords: ['amor', 'naranja'] },
            { emoji: '💛', name: 'corazón amarillo', keywords: ['amor', 'amarillo'] },
            { emoji: '💚', name: 'corazón verde', keywords: ['amor', 'verde'] },
            { emoji: '💙', name: 'corazón azul', keywords: ['amor', 'azul'] },
            { emoji: '💜', name: 'corazón púrpura', keywords: ['amor', 'morado'] },
            { emoji: '🖤', name: 'corazón negro', keywords: ['amor', 'oscuro'] },
            { emoji: '🤍', name: 'corazón blanco', keywords: ['amor', 'puro'] },
            { emoji: '🤎', name: 'corazón marrón', keywords: ['amor', 'café'] },
            { emoji: '💔', name: 'corazón roto', keywords: ['triste', 'desamor'] },
            { emoji: '❣️', name: 'corazón como exclamación', keywords: ['amor', 'énfasis'] },
            { emoji: '💕', name: 'dos corazones', keywords: ['amor', 'cariño'] },
            { emoji: '💞', name: 'corazones girando', keywords: ['amor', 'romance'] },
            { emoji: '💓', name: 'corazón latiendo', keywords: ['amor', 'latido'] },
            { emoji: '💗', name: 'corazón creciendo', keywords: ['amor', 'grande'] },
            { emoji: '💖', name: 'corazón brillante', keywords: ['amor', 'brillo'] },
            { emoji: '💘', name: 'corazón con flecha', keywords: ['cupido', 'enamorado'] },
            { emoji: '💝', name: 'corazón con lazo', keywords: ['regalo', 'amor'] },
            { emoji: '💟', name: 'decoración de corazón', keywords: ['amor', 'decoración'] },
            { emoji: '❤️‍🔥', name: 'corazón en llamas', keywords: ['pasión', 'ardiente'] },
            { emoji: '❤️‍🩹', name: 'corazón vendado', keywords: ['curación', 'recuperación'] },
            { emoji: '💋', name: 'marca de beso', keywords: ['beso', 'labios'] },
            { emoji: '💌', name: 'carta de amor', keywords: ['amor', 'carta'] },
            { emoji: '💐', name: 'ramo de flores', keywords: ['flores', 'regalo'] },
            { emoji: '🌹', name: 'rosa', keywords: ['flor', 'amor'] },
            { emoji: '🥀', name: 'flor marchita', keywords: ['triste', 'muerta'] },
            { emoji: '💍', name: 'anillo', keywords: ['matrimonio', 'compromiso'] },
            { emoji: '💎', name: 'diamante', keywords: ['joya', 'valioso'] },
        ],
    },
    {
        id: 'celebration',
        name: 'Celebración',
        icon: '🎉',
        emojis: [
            { emoji: '🎉', name: 'cañón de confeti', keywords: ['fiesta', 'celebración'] },
            { emoji: '🎊', name: 'bola de confeti', keywords: ['fiesta', 'celebración'] },
            { emoji: '🎈', name: 'globo', keywords: ['fiesta', 'cumpleaños'] },
            { emoji: '🎂', name: 'pastel de cumpleaños', keywords: ['cumpleaños', 'pastel'] },
            { emoji: '🎁', name: 'regalo envuelto', keywords: ['regalo', 'cumpleaños'] },
            { emoji: '🎀', name: 'lazo', keywords: ['regalo', 'decoración'] },
            { emoji: '🎄', name: 'árbol de navidad', keywords: ['navidad', 'festivo'] },
            { emoji: '🎃', name: 'calabaza de halloween', keywords: ['halloween', 'otoño'] },
            { emoji: '🎆', name: 'fuegos artificiales', keywords: ['celebración', 'año nuevo'] },
            { emoji: '🎇', name: 'bengala', keywords: ['celebración', 'fuego'] },
            { emoji: '🧨', name: 'petardo', keywords: ['explosión', 'celebración'] },
            { emoji: '✨', name: 'destellos', keywords: ['brillante', 'magia'] },
            { emoji: '🎗️', name: 'lazo de concienciación', keywords: ['apoyo', 'causa'] },
            { emoji: '🏆', name: 'trofeo', keywords: ['ganador', 'premio'] },
            { emoji: '🥇', name: 'medalla de oro', keywords: ['primero', 'ganador'] },
            { emoji: '🥈', name: 'medalla de plata', keywords: ['segundo', 'premio'] },
            { emoji: '🥉', name: 'medalla de bronce', keywords: ['tercero', 'premio'] },
            { emoji: '🏅', name: 'medalla deportiva', keywords: ['premio', 'deporte'] },
            { emoji: '🎖️', name: 'medalla militar', keywords: ['honor', 'militar'] },
            { emoji: '🎪', name: 'carpa de circo', keywords: ['circo', 'espectáculo'] },
            { emoji: '🎭', name: 'máscaras de teatro', keywords: ['teatro', 'drama'] },
            { emoji: '🎨', name: 'paleta de pintor', keywords: ['arte', 'pintura'] },
            { emoji: '🎬', name: 'claqueta', keywords: ['película', 'cine'] },
            { emoji: '🎤', name: 'micrófono', keywords: ['cantar', 'karaoke'] },
            { emoji: '🎧', name: 'auriculares', keywords: ['música', 'escuchar'] },
            { emoji: '🎼', name: 'partitura', keywords: ['música', 'notas'] },
            { emoji: '🎹', name: 'teclado musical', keywords: ['piano', 'música'] },
            { emoji: '🎷', name: 'saxofón', keywords: ['jazz', 'música'] },
            { emoji: '🎸', name: 'guitarra', keywords: ['rock', 'música'] },
            { emoji: '🎺', name: 'trompeta', keywords: ['música', 'banda'] },
            { emoji: '🎻', name: 'violín', keywords: ['clásica', 'música'] },
            { emoji: '🪘', name: 'tambor', keywords: ['música', 'ritmo'] },
            { emoji: '🎵', name: 'nota musical', keywords: ['música', 'canción'] },
            { emoji: '🎶', name: 'notas musicales', keywords: ['música', 'melodía'] },
        ],
    },
    {
        id: 'objects',
        name: 'Objetos',
        icon: '💼',
        emojis: [
            { emoji: '💼', name: 'maletín', keywords: ['trabajo', 'negocio'] },
            { emoji: '📱', name: 'teléfono móvil', keywords: ['celular', 'smartphone'] },
            { emoji: '📲', name: 'teléfono con flecha', keywords: ['llamada', 'mensaje'] },
            { emoji: '💻', name: 'portátil', keywords: ['computadora', 'laptop'] },
            { emoji: '🖥️', name: 'ordenador de escritorio', keywords: ['pc', 'computadora'] },
            { emoji: '🖨️', name: 'impresora', keywords: ['imprimir', 'oficina'] },
            { emoji: '⌨️', name: 'teclado', keywords: ['escribir', 'computadora'] },
            { emoji: '🖱️', name: 'ratón', keywords: ['clic', 'computadora'] },
            { emoji: '💿', name: 'cd', keywords: ['disco', 'música'] },
            { emoji: '📷', name: 'cámara', keywords: ['foto', 'fotografía'] },
            { emoji: '📹', name: 'videocámara', keywords: ['video', 'grabar'] },
            { emoji: '📺', name: 'televisor', keywords: ['tv', 'ver'] },
            { emoji: '📻', name: 'radio', keywords: ['música', 'escuchar'] },
            { emoji: '🔋', name: 'batería', keywords: ['energía', 'carga'] },
            { emoji: '🔌', name: 'enchufe', keywords: ['electricidad', 'conectar'] },
            { emoji: '💡', name: 'bombilla', keywords: ['idea', 'luz'] },
            { emoji: '🔦', name: 'linterna', keywords: ['luz', 'oscuro'] },
            { emoji: '📚', name: 'libros', keywords: ['leer', 'estudiar'] },
            { emoji: '📖', name: 'libro abierto', keywords: ['leer', 'estudio'] },
            { emoji: '📝', name: 'nota', keywords: ['escribir', 'papel'] },
            { emoji: '✏️', name: 'lápiz', keywords: ['escribir', 'dibujar'] },
            { emoji: '🖊️', name: 'bolígrafo', keywords: ['escribir', 'firma'] },
            { emoji: '📎', name: 'clip', keywords: ['adjuntar', 'oficina'] },
            { emoji: '📌', name: 'chincheta', keywords: ['fijar', 'nota'] },
            { emoji: '📍', name: 'chincheta redonda', keywords: ['ubicación', 'lugar'] },
            { emoji: '🔒', name: 'candado cerrado', keywords: ['seguro', 'privado'] },
            { emoji: '🔓', name: 'candado abierto', keywords: ['desbloqueado', 'acceso'] },
            { emoji: '🔑', name: 'llave', keywords: ['acceso', 'abrir'] },
            { emoji: '🔨', name: 'martillo', keywords: ['herramienta', 'construir'] },
            { emoji: '🔧', name: 'llave inglesa', keywords: ['herramienta', 'reparar'] },
            { emoji: '🔩', name: 'tornillo y tuerca', keywords: ['herramienta', 'fijar'] },
            { emoji: '⚙️', name: 'engranaje', keywords: ['configuración', 'ajustes'] },
            { emoji: '💰', name: 'bolsa de dinero', keywords: ['dinero', 'rico'] },
            { emoji: '💵', name: 'billete de dólar', keywords: ['dinero', 'efectivo'] },
            { emoji: '💳', name: 'tarjeta de crédito', keywords: ['pagar', 'comprar'] },
            { emoji: '📧', name: 'correo electrónico', keywords: ['email', 'mensaje'] },
            { emoji: '📨', name: 'sobre entrante', keywords: ['correo', 'mensaje'] },
            { emoji: '📩', name: 'sobre con flecha', keywords: ['correo', 'enviar'] },
            { emoji: '📦', name: 'paquete', keywords: ['caja', 'envío'] },
            { emoji: '🛒', name: 'carrito de compras', keywords: ['comprar', 'tienda'] },
        ],
    },
    {
        id: 'nature',
        name: 'Naturaleza',
        icon: '🌍',
        emojis: [
            { emoji: '🌍', name: 'globo terráqueo Europa-África', keywords: ['tierra', 'mundo'] },
            { emoji: '🌎', name: 'globo terráqueo América', keywords: ['tierra', 'mundo'] },
            { emoji: '🌏', name: 'globo terráqueo Asia-Australia', keywords: ['tierra', 'mundo'] },
            { emoji: '🌞', name: 'sol con cara', keywords: ['sol', 'día'] },
            { emoji: '🌝', name: 'luna llena con cara', keywords: ['luna', 'noche'] },
            { emoji: '⭐', name: 'estrella', keywords: ['favorito', 'brillante'] },
            { emoji: '🌟', name: 'estrella brillante', keywords: ['destacado', 'especial'] },
            { emoji: '💫', name: 'estrella fugaz', keywords: ['mareo', 'asombro'] },
            { emoji: '🌈', name: 'arcoíris', keywords: ['colores', 'lluvia'] },
            { emoji: '☁️', name: 'nube', keywords: ['cielo', 'clima'] },
            { emoji: '⛅', name: 'sol detrás de nube', keywords: ['parcialmente nublado'] },
            { emoji: '🌧️', name: 'nube con lluvia', keywords: ['lluvioso', 'clima'] },
            { emoji: '⛈️', name: 'nube con rayo y lluvia', keywords: ['tormenta', 'clima'] },
            { emoji: '❄️', name: 'copo de nieve', keywords: ['frío', 'invierno'] },
            { emoji: '🔥', name: 'fuego', keywords: ['caliente', 'trending'] },
            { emoji: '💧', name: 'gota de agua', keywords: ['agua', 'sudor'] },
            { emoji: '🌊', name: 'ola', keywords: ['mar', 'océano'] },
            { emoji: '🌸', name: 'flor de cerezo', keywords: ['primavera', 'japonés'] },
            { emoji: '🌺', name: 'hibisco', keywords: ['flor', 'tropical'] },
            { emoji: '🌻', name: 'girasol', keywords: ['flor', 'amarillo'] },
            { emoji: '🌼', name: 'flor', keywords: ['margarita', 'primavera'] },
            { emoji: '🌷', name: 'tulipán', keywords: ['flor', 'primavera'] },
            { emoji: '🌱', name: 'brote', keywords: ['crecer', 'planta'] },
            { emoji: '🌲', name: 'árbol de hoja perenne', keywords: ['pino', 'navidad'] },
            { emoji: '🌳', name: 'árbol de hoja caduca', keywords: ['árbol', 'naturaleza'] },
            { emoji: '🌴', name: 'palmera', keywords: ['tropical', 'playa'] },
            { emoji: '🌵', name: 'cactus', keywords: ['desierto', 'planta'] },
            { emoji: '🍀', name: 'trébol de cuatro hojas', keywords: ['suerte', 'irlandés'] },
            { emoji: '🍁', name: 'hoja de arce', keywords: ['otoño', 'canadá'] },
            { emoji: '🍂', name: 'hojas caídas', keywords: ['otoño', 'naturaleza'] },
            { emoji: '🐶', name: 'cara de perro', keywords: ['perro', 'mascota'] },
            { emoji: '🐱', name: 'cara de gato', keywords: ['gato', 'mascota'] },
            { emoji: '🐭', name: 'cara de ratón', keywords: ['ratón', 'animal'] },
            { emoji: '🐹', name: 'cara de hámster', keywords: ['hámster', 'mascota'] },
            { emoji: '🐰', name: 'cara de conejo', keywords: ['conejo', 'animal'] },
            { emoji: '🦊', name: 'cara de zorro', keywords: ['zorro', 'astuto'] },
            { emoji: '🐻', name: 'cara de oso', keywords: ['oso', 'animal'] },
            { emoji: '🐼', name: 'cara de panda', keywords: ['panda', 'animal'] },
            { emoji: '🐨', name: 'cara de koala', keywords: ['koala', 'australia'] },
            { emoji: '🐯', name: 'cara de tigre', keywords: ['tigre', 'animal'] },
            { emoji: '🦁', name: 'cara de león', keywords: ['león', 'rey'] },
            { emoji: '🐮', name: 'cara de vaca', keywords: ['vaca', 'animal'] },
            { emoji: '🐷', name: 'cara de cerdo', keywords: ['cerdo', 'animal'] },
            { emoji: '🐸', name: 'cara de rana', keywords: ['rana', 'sapo'] },
            { emoji: '🐵', name: 'cara de mono', keywords: ['mono', 'animal'] },
            { emoji: '🙈', name: 'mono tapándose los ojos', keywords: ['no ver', 'vergüenza'] },
            { emoji: '🙉', name: 'mono tapándose los oídos', keywords: ['no oír', 'ignorar'] },
            { emoji: '🙊', name: 'mono tapándose la boca', keywords: ['no hablar', 'secreto'] },
            { emoji: '🐔', name: 'pollo', keywords: ['gallina', 'animal'] },
            { emoji: '🐧', name: 'pingüino', keywords: ['antártida', 'animal'] },
            { emoji: '🐦', name: 'pájaro', keywords: ['ave', 'volar'] },
            { emoji: '🦋', name: 'mariposa', keywords: ['insecto', 'bonita'] },
            { emoji: '🐛', name: 'oruga', keywords: ['insecto', 'bicho'] },
            { emoji: '🐝', name: 'abeja', keywords: ['insecto', 'miel'] },
            { emoji: '🐞', name: 'mariquita', keywords: ['insecto', 'suerte'] },
            { emoji: '🦀', name: 'cangrejo', keywords: ['mar', 'animal'] },
            { emoji: '🐙', name: 'pulpo', keywords: ['mar', 'tentáculos'] },
            { emoji: '🐚', name: 'concha', keywords: ['mar', 'playa'] },
            { emoji: '🐠', name: 'pez tropical', keywords: ['pez', 'acuario'] },
            { emoji: '🐳', name: 'ballena', keywords: ['océano', 'grande'] },
            { emoji: '🦈', name: 'tiburón', keywords: ['peligro', 'mar'] },
            { emoji: '🐊', name: 'cocodrilo', keywords: ['reptil', 'peligro'] },
            { emoji: '🦎', name: 'lagartija', keywords: ['reptil', 'animal'] },
            { emoji: '🐍', name: 'serpiente', keywords: ['reptil', 'peligro'] },
            { emoji: '🦕', name: 'dinosaurio', keywords: ['prehistórico', 'animal'] },
            { emoji: '🦖', name: 'T-Rex', keywords: ['dinosaurio', 'prehistórico'] },
        ],
    },
    {
        id: 'food',
        name: 'Comida',
        icon: '🍕',
        emojis: [
            { emoji: '🍕', name: 'pizza', keywords: ['comida', 'italiano'] },
            { emoji: '🍔', name: 'hamburguesa', keywords: ['comida', 'rápida'] },
            { emoji: '🍟', name: 'papas fritas', keywords: ['patatas', 'comida'] },
            { emoji: '🌭', name: 'perrito caliente', keywords: ['hot dog', 'comida'] },
            { emoji: '🥪', name: 'sándwich', keywords: ['comida', 'almuerzo'] },
            { emoji: '🌮', name: 'taco', keywords: ['mexicano', 'comida'] },
            { emoji: '🌯', name: 'burrito', keywords: ['mexicano', 'comida'] },
            { emoji: '🥗', name: 'ensalada', keywords: ['saludable', 'vegetales'] },
            { emoji: '🍝', name: 'espagueti', keywords: ['pasta', 'italiano'] },
            { emoji: '🍜', name: 'sopa de fideos', keywords: ['ramen', 'asiático'] },
            { emoji: '🍲', name: 'olla de comida', keywords: ['sopa', 'guiso'] },
            { emoji: '🍛', name: 'curry y arroz', keywords: ['indio', 'comida'] },
            { emoji: '🍣', name: 'sushi', keywords: ['japonés', 'comida'] },
            { emoji: '🍱', name: 'bento', keywords: ['japonés', 'comida'] },
            { emoji: '🥟', name: 'dumpling', keywords: ['asiático', 'comida'] },
            { emoji: '🍳', name: 'huevo frito', keywords: ['desayuno', 'cocinar'] },
            { emoji: '🥚', name: 'huevo', keywords: ['comida', 'ingrediente'] },
            { emoji: '🧀', name: 'queso', keywords: ['lácteo', 'comida'] },
            { emoji: '🥩', name: 'carne', keywords: ['filete', 'comida'] },
            { emoji: '🍗', name: 'muslo de pollo', keywords: ['pollo', 'comida'] },
            { emoji: '🥓', name: 'tocino', keywords: ['bacon', 'desayuno'] },
            { emoji: '🍞', name: 'pan', keywords: ['comida', 'carbohidrato'] },
            { emoji: '🥐', name: 'croissant', keywords: ['francés', 'desayuno'] },
            { emoji: '🥖', name: 'baguette', keywords: ['pan', 'francés'] },
            { emoji: '🧇', name: 'waffle', keywords: ['desayuno', 'dulce'] },
            { emoji: '🥞', name: 'panqueques', keywords: ['desayuno', 'dulce'] },
            { emoji: '🍰', name: 'pastel', keywords: ['postre', 'dulce'] },
            { emoji: '🎂', name: 'pastel de cumpleaños', keywords: ['cumpleaños', 'celebración'] },
            { emoji: '🧁', name: 'cupcake', keywords: ['postre', 'dulce'] },
            { emoji: '🍩', name: 'dona', keywords: ['dulce', 'postre'] },
            { emoji: '🍪', name: 'galleta', keywords: ['dulce', 'postre'] },
            { emoji: '🍫', name: 'chocolate', keywords: ['dulce', 'postre'] },
            { emoji: '🍬', name: 'caramelo', keywords: ['dulce', 'postre'] },
            { emoji: '🍭', name: 'piruleta', keywords: ['dulce', 'postre'] },
            { emoji: '🍦', name: 'helado', keywords: ['postre', 'frío'] },
            { emoji: '🍧', name: 'helado raspado', keywords: ['postre', 'frío'] },
            { emoji: '🍨', name: 'helado en copa', keywords: ['postre', 'frío'] },
            { emoji: '🍎', name: 'manzana roja', keywords: ['fruta', 'saludable'] },
            { emoji: '🍊', name: 'naranja', keywords: ['fruta', 'cítrico'] },
            { emoji: '🍋', name: 'limón', keywords: ['fruta', 'cítrico'] },
            { emoji: '🍌', name: 'plátano', keywords: ['fruta', 'banana'] },
            { emoji: '🍉', name: 'sandía', keywords: ['fruta', 'verano'] },
            { emoji: '🍇', name: 'uvas', keywords: ['fruta', 'vino'] },
            { emoji: '🍓', name: 'fresa', keywords: ['fruta', 'roja'] },
            { emoji: '🫐', name: 'arándano', keywords: ['fruta', 'berry'] },
            { emoji: '🍑', name: 'durazno', keywords: ['fruta', 'peach'] },
            { emoji: '🥭', name: 'mango', keywords: ['fruta', 'tropical'] },
            { emoji: '🍍', name: 'piña', keywords: ['fruta', 'tropical'] },
            { emoji: '🥥', name: 'coco', keywords: ['fruta', 'tropical'] },
            { emoji: '🥑', name: 'aguacate', keywords: ['fruta', 'guacamole'] },
            { emoji: '🍆', name: 'berenjena', keywords: ['vegetal', 'morado'] },
            { emoji: '🥕', name: 'zanahoria', keywords: ['vegetal', 'naranja'] },
            { emoji: '🌽', name: 'maíz', keywords: ['vegetal', 'elote'] },
            { emoji: '🌶️', name: 'chile', keywords: ['picante', 'vegetal'] },
            { emoji: '🥒', name: 'pepino', keywords: ['vegetal', 'verde'] },
            { emoji: '🥬', name: 'lechuga', keywords: ['vegetal', 'ensalada'] },
            { emoji: '🍄', name: 'hongo', keywords: ['champiñón', 'vegetal'] },
            { emoji: '☕', name: 'café caliente', keywords: ['café', 'bebida'] },
            { emoji: '🍵', name: 'té', keywords: ['bebida', 'caliente'] },
            { emoji: '🧃', name: 'jugo en caja', keywords: ['bebida', 'jugo'] },
            { emoji: '🥤', name: 'vaso con popote', keywords: ['bebida', 'refresco'] },
            { emoji: '🧊', name: 'cubo de hielo', keywords: ['frío', 'hielo'] },
            { emoji: '🍺', name: 'cerveza', keywords: ['bebida', 'alcohol'] },
            { emoji: '🍷', name: 'vino', keywords: ['bebida', 'alcohol'] },
            { emoji: '🍸', name: 'cóctel', keywords: ['bebida', 'alcohol'] },
            { emoji: '🍹', name: 'bebida tropical', keywords: ['cóctel', 'alcohol'] },
            { emoji: '🥂', name: 'brindis', keywords: ['celebración', 'champán'] },
        ],
    },
    {
        id: 'sports',
        name: 'Deportes',
        icon: '⚽',
        emojis: [
            { emoji: '⚽', name: 'balón de fútbol', keywords: ['fútbol', 'deporte'] },
            { emoji: '🏀', name: 'balón de baloncesto', keywords: ['basketball', 'deporte'] },
            { emoji: '🏈', name: 'balón de fútbol americano', keywords: ['football', 'deporte'] },
            { emoji: '⚾', name: 'béisbol', keywords: ['pelota', 'deporte'] },
            { emoji: '🥎', name: 'softball', keywords: ['pelota', 'deporte'] },
            { emoji: '🎾', name: 'tenis', keywords: ['pelota', 'deporte'] },
            { emoji: '🏐', name: 'voleibol', keywords: ['pelota', 'deporte'] },
            { emoji: '🏉', name: 'rugby', keywords: ['pelota', 'deporte'] },
            { emoji: '🥏', name: 'frisbee', keywords: ['disco', 'juego'] },
            { emoji: '🎱', name: 'billar', keywords: ['bola', 'juego'] },
            { emoji: '🏓', name: 'ping pong', keywords: ['tenis de mesa', 'deporte'] },
            { emoji: '🏸', name: 'bádminton', keywords: ['raqueta', 'deporte'] },
            { emoji: '🏒', name: 'hockey sobre hielo', keywords: ['hockey', 'deporte'] },
            { emoji: '🏑', name: 'hockey sobre campo', keywords: ['hockey', 'deporte'] },
            { emoji: '🥍', name: 'lacrosse', keywords: ['deporte', 'juego'] },
            { emoji: '🏏', name: 'cricket', keywords: ['deporte', 'bate'] },
            { emoji: '⛳', name: 'golf', keywords: ['deporte', 'hoyo'] },
            { emoji: '🏌️', name: 'golfista', keywords: ['golf', 'deporte'] },
            { emoji: '🏊', name: 'nadador', keywords: ['natación', 'deporte'] },
            { emoji: '🏄', name: 'surfista', keywords: ['surf', 'deporte'] },
            { emoji: '🚣', name: 'remador', keywords: ['remo', 'deporte'] },
            { emoji: '🧗', name: 'escalador', keywords: ['escalada', 'deporte'] },
            { emoji: '🚴', name: 'ciclista', keywords: ['bicicleta', 'deporte'] },
            { emoji: '🏃', name: 'corredor', keywords: ['correr', 'atletismo'] },
            { emoji: '🚶', name: 'caminando', keywords: ['caminar', 'persona'] },
            { emoji: '🧘', name: 'yoga', keywords: ['meditación', 'relajación'] },
            { emoji: '🤸', name: 'voltereta', keywords: ['gimnasia', 'acrobacia'] },
            { emoji: '⛷️', name: 'esquiador', keywords: ['esquí', 'nieve'] },
            { emoji: '🏂', name: 'snowboarder', keywords: ['snowboard', 'nieve'] },
            { emoji: '🥊', name: 'guante de boxeo', keywords: ['boxeo', 'pelea'] },
            { emoji: '🥋', name: 'uniforme de artes marciales', keywords: ['karate', 'judo'] },
            { emoji: '🎯', name: 'diana', keywords: ['objetivo', 'tiro'] },
            { emoji: '🎳', name: 'bolos', keywords: ['bowling', 'juego'] },
            { emoji: '🎮', name: 'control de videojuegos', keywords: ['gaming', 'videojuegos'] },
            { emoji: '🕹️', name: 'joystick', keywords: ['gaming', 'arcade'] },
            { emoji: '🎰', name: 'máquina tragamonedas', keywords: ['casino', 'juego'] },
            { emoji: '🎲', name: 'dado', keywords: ['juego', 'azar'] },
            { emoji: '♟️', name: 'peón de ajedrez', keywords: ['ajedrez', 'juego'] },
            { emoji: '🧩', name: 'puzzle', keywords: ['rompecabezas', 'juego'] },
        ],
    },
    {
        id: 'symbols',
        name: 'Símbolos',
        icon: '🚩',
        emojis: [
            { emoji: '✅', name: 'marca de verificación', keywords: ['correcto', 'hecho'] },
            { emoji: '❌', name: 'marca de cruz', keywords: ['incorrecto', 'no'] },
            { emoji: '❓', name: 'signo de interrogación', keywords: ['pregunta', 'duda'] },
            { emoji: '❗', name: 'signo de exclamación', keywords: ['atención', 'importante'] },
            { emoji: '⚠️', name: 'advertencia', keywords: ['peligro', 'cuidado'] },
            { emoji: '🚫', name: 'prohibido', keywords: ['no', 'prohibición'] },
            { emoji: '⛔', name: 'entrada prohibida', keywords: ['no pasar', 'stop'] },
            { emoji: '🔴', name: 'círculo rojo', keywords: ['rojo', 'punto'] },
            { emoji: '🟠', name: 'círculo naranja', keywords: ['naranja', 'punto'] },
            { emoji: '🟡', name: 'círculo amarillo', keywords: ['amarillo', 'punto'] },
            { emoji: '🟢', name: 'círculo verde', keywords: ['verde', 'punto'] },
            { emoji: '🔵', name: 'círculo azul', keywords: ['azul', 'punto'] },
            { emoji: '🟣', name: 'círculo púrpura', keywords: ['morado', 'punto'] },
            { emoji: '⚫', name: 'círculo negro', keywords: ['negro', 'punto'] },
            { emoji: '⚪', name: 'círculo blanco', keywords: ['blanco', 'punto'] },
            { emoji: '🔶', name: 'rombo naranja', keywords: ['naranja', 'forma'] },
            { emoji: '🔷', name: 'rombo azul', keywords: ['azul', 'forma'] },
            { emoji: '🔺', name: 'triángulo rojo hacia arriba', keywords: ['arriba', 'forma'] },
            { emoji: '🔻', name: 'triángulo rojo hacia abajo', keywords: ['abajo', 'forma'] },
            { emoji: '➕', name: 'signo de más', keywords: ['sumar', 'agregar'] },
            { emoji: '➖', name: 'signo de menos', keywords: ['restar', 'quitar'] },
            { emoji: '➗', name: 'signo de división', keywords: ['dividir', 'matemáticas'] },
            { emoji: '✖️', name: 'signo de multiplicación', keywords: ['multiplicar', 'matemáticas'] },
            { emoji: '♾️', name: 'infinito', keywords: ['infinito', 'eterno'] },
            { emoji: '💯', name: 'cien puntos', keywords: ['perfecto', '100'] },
            { emoji: '🔢', name: 'números', keywords: ['123', 'matemáticas'] },
            { emoji: '🔤', name: 'letras', keywords: ['abc', 'alfabeto'] },
            { emoji: '🆕', name: 'nuevo', keywords: ['new', 'reciente'] },
            { emoji: '🆒', name: 'cool', keywords: ['genial', 'increíble'] },
            { emoji: '🆓', name: 'gratis', keywords: ['free', 'sin costo'] },
            { emoji: '🆗', name: 'ok', keywords: ['bien', 'aceptar'] },
            { emoji: '🆘', name: 'sos', keywords: ['ayuda', 'emergencia'] },
            { emoji: '🏳️', name: 'bandera blanca', keywords: ['rendirse', 'paz'] },
            { emoji: '🏴', name: 'bandera negra', keywords: ['pirata', 'oscuro'] },
            { emoji: '🚩', name: 'bandera triangular', keywords: ['bandera', 'marca'] },
            { emoji: '🎌', name: 'banderas cruzadas', keywords: ['celebración', 'japón'] },
            { emoji: '🏁', name: 'bandera a cuadros', keywords: ['meta', 'carrera'] },
            { emoji: '♻️', name: 'símbolo de reciclaje', keywords: ['reciclar', 'ecología'] },
            { emoji: '⚡', name: 'rayo', keywords: ['electricidad', 'energía'] },
            { emoji: '🌐', name: 'globo con meridianos', keywords: ['internet', 'web'] },
            { emoji: 'ℹ️', name: 'información', keywords: ['info', 'ayuda'] },
            { emoji: '🔗', name: 'eslabones', keywords: ['enlace', 'link'] },
            { emoji: '#️⃣', name: 'tecla numeral', keywords: ['hashtag', 'número'] },
            { emoji: '*️⃣', name: 'tecla asterisco', keywords: ['asterisco', 'estrella'] },
            { emoji: '0️⃣', name: 'tecla cero', keywords: ['cero', 'número'] },
            { emoji: '1️⃣', name: 'tecla uno', keywords: ['uno', 'número'] },
            { emoji: '2️⃣', name: 'tecla dos', keywords: ['dos', 'número'] },
            { emoji: '3️⃣', name: 'tecla tres', keywords: ['tres', 'número'] },
            { emoji: '4️⃣', name: 'tecla cuatro', keywords: ['cuatro', 'número'] },
            { emoji: '5️⃣', name: 'tecla cinco', keywords: ['cinco', 'número'] },
            { emoji: '6️⃣', name: 'tecla seis', keywords: ['seis', 'número'] },
            { emoji: '7️⃣', name: 'tecla siete', keywords: ['siete', 'número'] },
            { emoji: '8️⃣', name: 'tecla ocho', keywords: ['ocho', 'número'] },
            { emoji: '9️⃣', name: 'tecla nueve', keywords: ['nueve', 'número'] },
            { emoji: '🔟', name: 'tecla diez', keywords: ['diez', 'número'] },
        ],
    },
];

// Get recent emojis from localStorage
export function getRecentEmojis(): Emoji[] {
    try {
        const stored = localStorage.getItem(RECENT_EMOJIS_KEY);
        if (stored) {
            return JSON.parse(stored);
        }
    } catch (error) {
        console.error('Error reading recent emojis:', error);
    }
    return [];
}

// Add emoji to recent emojis
export function addRecentEmoji(emoji: Emoji): void {
    try {
        const recent = getRecentEmojis();
        // Remove if already exists
        const filtered = recent.filter((e) => e.emoji !== emoji.emoji);
        // Add to beginning
        const updated = [emoji, ...filtered].slice(0, MAX_RECENT_EMOJIS);
        localStorage.setItem(RECENT_EMOJIS_KEY, JSON.stringify(updated));
    } catch (error) {
        console.error('Error saving recent emoji:', error);
    }
}

// Search emojis by name, keywords or character
export function searchEmojis(query: string): Emoji[] {
    const normalizedQuery = query.toLowerCase().trim();
    if (!normalizedQuery) return [];

    const results: Emoji[] = [];

    for (const category of emojiCategories) {
        if (category.id === 'recent') continue;

        for (const emoji of category.emojis) {
            // Check if emoji matches the query
            if (emoji.emoji.includes(query)) {
                results.push(emoji);
                continue;
            }

            // Check name
            if (emoji.name.toLowerCase().includes(normalizedQuery)) {
                results.push(emoji);
                continue;
            }

            // Check keywords
            if (emoji.keywords.some((kw) => kw.toLowerCase().includes(normalizedQuery))) {
                results.push(emoji);
            }
        }
    }

    return results;
}

// Get all emojis as a flat list
export function getAllEmojis(): Emoji[] {
    const all: Emoji[] = [];
    for (const category of emojiCategories) {
        if (category.id === 'recent') continue;
        all.push(...category.emojis);
    }
    return all;
}

// Get categories with recent emojis populated
export function getCategoriesWithRecent(): EmojiCategory[] {
    const recent = getRecentEmojis();
    return emojiCategories.map((category) => {
        if (category.id === 'recent') {
            return { ...category, emojis: recent };
        }
        return category;
    });
}
